[phases.setup]
nixPkgs = ["vips", "pkg-config", "python3"]

[phases.install]
cmds = ["npm ci --ignore-scripts", "npm rebuild sharp", "npm rebuild @xenova/transformers --if-present"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
